### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dicearr** [dicearr/koa-rester#1]
This list contains almost all the functionalities that i would like to develop.

- [ ] Add usage examples to the wiki
- [ ] Add information about how to add own KoaResterPersistence 
- [x] Swagger documentation for the created endpoints
- [x] Add logger support
- [x] Add before/after options for list, post, get, patch, delete and rest.
- [x] Add before/after operation options for rest (beforeList, beforePost...)
- [ ] Be able to filter/order GET /resource by using query parameters
